version: '3.8'

services:
  flask-server:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: user-management-server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      # Mount data directory for persistent SQLite database
      - ../data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a development service
  flask-server-dev:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: user-management-server-dev
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PORT=5000
    volumes:
      # Mount source code for development
      - ..:/app
      - ../data:/app/data
    restart: unless-stopped
    profiles:
      - dev